"""Add sex and contact number on user

Revision ID: 03f9b446880a
Revises: 8cd695e7da3c
Create Date: 2025-07-14 13:51:11.024007

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "03f9b446880a"
down_revision: Union[str, Sequence[str], None] = "8cd695e7da3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("sex", sa.String(), nullable=True))
    op.add_column("users", sa.Column("contact_number", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "users", ["contact_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "contact_number")
    op.drop_column("users", "sex")
    # ### end Alembic commands ###
