"""Update contact number from int to str

Revision ID: 70105cc1a508
Revises: 03f9b446880a
Create Date: 2025-07-14 13:58:26.573091

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "70105cc1a508"
down_revision: Union[str, Sequence[str], None] = "03f9b446880a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "sex", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "users",
        "contact_number",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=11),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "contact_number",
        existing_type=sa.String(length=11),
        type_=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column("users", "sex", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
