"""Update contact and sex to be nullable=False

Revision ID: a43aa8648c6e
Revises: 70105cc1a508
Create Date: 2025-07-14 14:05:45.616494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a43aa8648c6e'
down_revision: Union[str, Sequence[str], None] = '70105cc1a508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sex',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'contact_number',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'contact_number',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.alter_column('users', 'sex',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
